name: PackPlugin
on:
    push:
        branches:
            - master

jobs:
    build:
        uses: FriendsOfShopware/actions/.github/workflows/store.yml@main
        with:
            extensionName: FroshPlatformBunnycdnMediaStorage
            shopwareVersion: '6.4.0'
            cliVersion: '0.1.50'
        secrets:
            accountUser: ${{ secrets.ACCOUNT_USER }}
            accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}
