name: StoreCheck
on:
    push:
        branches:
            - master
    release:
        types: [created]

env:
    PLUGIN_NAME: FroshPlatformBunnycdnMediaStorage
    PLUGIN_ID: ${{ secrets.PLUGIN_ID }}
    ACCOUNT_USER: ${{ secrets.ACCOUNT_USER }}
    ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}

jobs:
    validatePlugin:
        if: startsWith(github.ref, 'refs/tags/') != true
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            #            - name: Install dependencies
            #              run: composer install --prefer-dist --no-progress --no-suggest

            -   name: BuildZip
                run: |
                    ls
                    rm -rf ${PLUGIN_NAME}*.zip
                    ( find . -path *Resources/store && find . -type d -name "bin" && find . -type d -name ".git" && find . -type d -name ".github" && find . -name "build.sh"  && find . -name ".gitignore" && find . -name ".gitmodules" ) | xargs rm -r
                    zip -r ${PLUGIN_NAME}-${GITHUB_SHA}.zip ${PLUGIN_NAME}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.2.2/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: StoreCheck
                run: php frosh-plugin-upload.phar plugin:validate ${GITHUB_WORKSPACE}/${PLUGIN_NAME}-${GITHUB_SHA}.zip

    StoreUpdate:
        needs: validatePlugin
        if: startsWith(github.ref, 'refs/tags/') != true
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            #            - name: Install dependencies
            #              run: composer install --prefer-dist --no-progress --no-suggest

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.2.2/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: StoreUpdate
                run: php frosh-plugin-upload.phar plugin:update ${GITHUB_WORKSPACE}/${{ env.PLUGIN_NAME }}/

    StoreRelease:
        needs: StoreUpdate
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            #            - name: Install dependencies
            #              run: composer install --prefer-dist --no-progress --no-suggest

            -   name: BuildZip
                run: |
                    ls
                    rm -rf ${PLUGIN_NAME}*.zip
                    ( find . -path *Resources/store && find . -type d -name "bin" && find . -type d -name ".git" && find . -type d -name ".github" && find . -name "build.sh"  && find . -name ".gitignore" && find . -name ".gitmodules" ) | xargs rm -r
                    zip -r ${PLUGIN_NAME}-${GITHUB_SHA}.zip ${PLUGIN_NAME}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.2.2/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: StoreUpdate
                run: php frosh-plugin-upload.phar plugin:upload ${GITHUB_WORKSPACE}/${PLUGIN_NAME}-${GITHUB_SHA}.zip

            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1.0.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: Release ${{ github.ref }}
                    draft: false
                    prerelease: false

            -   name: Upload Release Asset
                id: upload_release_asset
                uses: actions/upload-release-asset@v1.0.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: ${{ github.workspace }}/${{ env.PLUGIN_NAME }}-${{ github.sha }}.zip
                    asset_name: ${{ env.PLUGIN_NAME }}.zip
                    asset_content_type: application/zip
