name: Test
on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: "5 15 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [ "v6.5.1", "v6.5.2", "v6.5.3", "v6.5.4", "trunk" ]
    container: ghcr.io/friendsofshopware/platform-plugin-dev:${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHPStan
        run: |
          mysql -V
          php -v
          cp -r "./" "/plugins/FroshPlatformBunnycdnMediaStorage"
          cd /plugins/FroshPlatformBunnycdnMediaStorage
          /opt/shopware/vendor/bin/phpstan analyse -c phpstan.neon
